name: "preprocess"
backend: "python"
max_batch_size: 64 
input [
    {
        name: "INPUT_0"
        data_type: TYPE_UINT8
        dims: [ -1 ]
    }
]
 
output [
    {
        name: "OUTPUT_0"
        data_type: TYPE_FP32
        dims: [ 3, -1, -1 ]
    }
]

instance_group [{ kind: KIND_CPU }]
