name: "yolo_detection"
platform: "onnxruntime_onnx"
max_batch_size: 256
input [
    {
        name: "images"
        data_type: TYPE_FP32
        dims: [ 3, -1, -1 ]
        
    }
]

output [
    {
        name: "output0"
        data_type: TYPE_FP32
        dims: [ -1, -1 ]
    }
]